### PR TITLE
Add readme, minions, kotlin, and make it a library

### PR DESCRIPTION
**Pull request by galaxygoldfish**
- kotlin
- minions
- library project structure
- use kotlin gradle DSL 
- please make this a jitpack thingy https://jitpack.io
- thank you

### CODE REVIEW

**Comment by kirbt** [comment]
this is so epic sauce #kotlin poggy woggy 🤪

**Review by TAKBS2412 — APPROVED** [review]
Eyes literally sobbing with joy reviewing this

**Review by jbko6 — CHANGES_REQUESTED** [review]
please convert the kotlin to java 😊😘

**Comment by galaxygoldfish** [comment]
😱😱😱

**Pull request merged**
